services:
  api:
    container_name: file-processor-api
    image: rajsekhar05/file-processor-api:latest
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./file-storage:/file-storage
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
  
  worker:
    container_name: file-processor-worker
    image: rajsekhar05/file-processor-worker:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./file-storage:/file-storage
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
  
  redis:
    container_name: file-processor-redis
    image: redis:alpine
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  app-network:
    driver: bridge